require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# unimodules
# require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
# unimodules
platform :ios, '10.0'

target 'GrouplyApp' do
  # unimodules
  # use_unimodules!
  # unimodules
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'GrouplyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'GrouplyApp-tvOS' do
  # Pods for GrouplyApp-tvOS

  target 'GrouplyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
